name: 'Configure environment'
description: 'Configure CI, cache and container name environment variables'
runs:
  using: 'composite'
  steps:
    - name: Set CI and cache directories
      shell: bash
      run: |
        BASE_ROOT_DIR="${{ runner.temp }}"
        BASE_ROOT_HASH="$(printf '%s' "$BASE_ROOT_DIR" | sha256sum | cut -d' ' -f1 | cut -c1-16)"
        echo "BASE_ROOT_DIR=$BASE_ROOT_DIR" >> "$GITHUB_ENV"
        echo "BASE_BUILD_DIR=$BASE_ROOT_DIR/build" >> "$GITHUB_ENV"
        echo "CCACHE_DIR=$BASE_ROOT_DIR/ccache_dir" >> $GITHUB_ENV
        echo "DEPENDS_DIR=$BASE_ROOT_DIR/depends" >> "$GITHUB_ENV"
        echo "BASE_CACHE=$BASE_ROOT_DIR/depends/built" >> $GITHUB_ENV
        echo "SOURCES_PATH=$BASE_ROOT_DIR/depends/sources" >> $GITHUB_ENV
        echo "DEPENDS_BUILT_CACHE_SUFFIX=$BASE_ROOT_HASH" >> "$GITHUB_ENV"

    - name: Set cache hashes
      shell: bash
      run: |
        echo "DEPENDS_HASH=$(git ls-tree HEAD depends "ci/test/$FILE_ENV" | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Get container name
      shell: bash
      run: |
        source $FILE_ENV
        echo "CONTAINER_NAME=$CONTAINER_NAME" >> "$GITHUB_ENV"
